import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    title: 'Pokédex',
    subtitle: 'Search for Pokémon by name or using the National Pokédex number.',
    searchPlaceholder: 'What Pokémon are you looking for?',
    noResultsTitle: "We couldn't find any Pokémon!",
    noResultsTip: 'Give these tips a try to refine your search:',
    noResultsTips: ['Use fewer search filters', 'Try using one Pokémon type at a time', 'Include different body dimensions'],
    sortTitle: 'Sort',
    sortSubtitle: 'Sort Pokémon alphabetically or by National Pokédex number!',
    sortOptions: { smallest: 'Smallest number first', highest: 'Highest number first', az: 'A-Z', za: 'Z-A' },
    filterTitle: 'Filters',
    filterSubtitle: 'Use advanced search to explore Pokémon by type, weakness, height and more!',
    filterTypes: 'Types',
    filterWeaknesses: 'Weaknesses',
    filterHeights: 'Heights',
    filterWeights: 'Weights',
    filterRange: 'Number Range',
    reset: 'Reset',
    apply: 'Apply',
    genTitle: 'Generations',
    genSubtitle: 'Use search for generations to explore your Pokémon!',
    genLabels: ['Generation I', 'Generation II', 'Generation III', 'Generation IV', 'Generation V', 'Generation VI', 'Generation VII', 'Generation VIII', 'Generation IX', 'Generation X'],
    comingSoon: 'Coming Soon',
    height: 'Height',
    weight: 'Weight',
    stats: 'Stats',
    tabAbout: 'About',
    tabStats: 'Stats',
    tabEvolution: 'Evolution',
    sectionPokedexData: 'Pokédex Data',
    sectionTraining: 'Training',
    sectionBreeding: 'Breeding',
    labelSpecies: 'Species',
    labelHeight: 'Height',
    labelWeight: 'Weight',
    labelAbilities: 'Abilities',
    labelWeaknesses: 'Weaknesses',
    labelEvYield: 'EV Yield',
    labelCatchRate: 'Catch Rate',
    labelBaseFriendship: 'Base Friendship',
    labelBaseExp: 'Base Exp',
    labelGrowthRate: 'Growth Rate',
    labelGender: 'Gender',
    labelEggGroups: 'Egg Groups',
    labelEggCycles: 'Egg Cycles',
    hiddenAbility: 'hidden ability',
    normal: 'normal',
    genderless: 'Genderless',
    withPokeball: 'with PokéBall, full HP',
    steps: 'steps',
    evolutionSoon: 'Evolution coming soon.',
    sectionPokedexEntry: 'Pokédex Entry',
    labelVersion: 'Version',
    apiLang: 'en',
  },
  pt: {
    title: 'Pokédex',
    subtitle: 'Busque Pokémon pelo nome ou pelo número da Pokédex Nacional.',
    searchPlaceholder: 'Qual Pokémon você está procurando?',
    noResultsTitle: 'Não achamos nenhum Pokémon!',
    noResultsTip: 'Tente essas dicas para refinar sua busca:',
    noResultsTips: ['Use menos filtros de busca', 'Tente usar um tipo de Pokémon por vez', 'Inclua diferentes dimensões corporais'],
    sortTitle: 'Ordenar',
    sortSubtitle: 'Ordene os Pokémon alfabeticamente ou pelo número da Pokédex Nacional!',
    sortOptions: { smallest: 'Menor número primeiro', highest: 'Maior número primeiro', az: 'A-Z', za: 'Z-A' },
    filterTitle: 'Filtros',
    filterSubtitle: 'Use a busca avançada para explorar Pokémon por tipo, fraqueza, altura e mais!',
    filterTypes: 'Tipos',
    filterWeaknesses: 'Fraquezas',
    filterHeights: 'Alturas',
    filterWeights: 'Pesos',
    filterRange: 'Intervalo de Número',
    reset: 'Resetar',
    apply: 'Aplicar',
    genTitle: 'Gerações',
    genSubtitle: 'Use a busca por gerações para explorar seus Pokémon!',
    genLabels: ['Geração I', 'Geração II', 'Geração III', 'Geração IV', 'Geração V', 'Geração VI', 'Geração VII', 'Geração VIII', 'Geração IX', 'Geração X'],
    comingSoon: 'Em Breve',
    height: 'Altura',
    weight: 'Peso',
    stats: 'Estatísticas',
    tabAbout: 'Sobre',
    tabStats: 'Estatísticas',
    tabEvolution: 'Evolução',
    sectionPokedexData: 'Dados da Pokédex',
    sectionTraining: 'Treinamento',
    sectionBreeding: 'Reprodução',
    labelSpecies: 'Espécie',
    labelHeight: 'Altura',
    labelWeight: 'Peso',
    labelAbilities: 'Habilidades',
    labelWeaknesses: 'Fraquezas',
    labelEvYield: 'Rendimento EV',
    labelCatchRate: 'Taxa de Captura',
    labelBaseFriendship: 'Amizade Base',
    labelBaseExp: 'Exp Base',
    labelGrowthRate: 'Taxa de Crescimento',
    labelGender: 'Gênero',
    labelEggGroups: 'Grupos de Ovo',
    labelEggCycles: 'Ciclos de Ovo',
    hiddenAbility: 'habilidade oculta',
    normal: 'normal',
    genderless: 'Sem Gênero',
    withPokeball: 'com PokéBall, HP cheio',
    steps: 'passos',
    evolutionSoon: 'Evolução em breve.',
    sectionPokedexEntry: 'Entrada da Pokédex',
    labelVersion: 'Versão',
    apiLang: 'pt',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const toggle = () => setLang(l => l === 'en' ? 'pt' : 'en')
  return (
    <LanguageContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
